services:

  # nginx
  webserver:
    restart: unless-stopped

    image: nginx:1.25.5
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/var/www

  # php
  app:
    restart: unless-stopped

    build:
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003"
    volumes:
      - ./:/var/www

  # postgresql
  db:
    restart: unless-stopped

    image: postgres:16
    volumes:
      - database:/var/lib/postgresql;
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  database: